local E, L, V, P, G = unpack(ElvUI)

P.DmgAtPlates = P.DmgAtPlates or {}
P.DmgAtPlates.onorof = P.DmgAtPlates.onorof or false
P.DmgAtPlates.showIcon = P.DmgAtPlates.showIcon or false
P.DmgAtPlates.font = P.DmgAtPlates.font or "PT Sans Narrow"
P.DmgAtPlates.fontSize = P.DmgAtPlates.fontSize or 20
P.DmgAtPlates.fontAlpha = P.DmgAtPlates.fontAlpha or 1
P.DmgAtPlates.fontOutline = P.DmgAtPlates.fontOutline or "OUTLINE"
P.DmgAtPlates.sfftrgt = P.DmgAtPlates.sfftrgt or false
P.DmgAtPlates.sfftrgtSize = P.DmgAtPlates.sfftrgtSize or 20
P.DmgAtPlates.sfftrgtAlpha = P.DmgAtPlates.sfftrgtAlpha or 1
P.DmgAtPlates.smallHits = P.DmgAtPlates.smallHits or false
P.DmgAtPlates.smallHitsScale = P.DmgAtPlates.smallHitsScale or 1
P.DmgAtPlates.smallHitsHide = P.DmgAtPlates.smallHitsHide or false
P.DmgAtPlates.textFormat = P.DmgAtPlates.textFormat or "none"
P.DmgAtPlates.pttdt = P.DmgAtPlates.pttdt or false
P.DmgAtPlates.ttpdt = P.DmgAtPlates.ttpdt or false
P.DmgAtPlates.petttdt = P.DmgAtPlates.petttdt or false
P.DmgAtPlates.tttckndcrt = P.DmgAtPlates.tttckndcrt or "verticalUp"
P.DmgAtPlates.tttck = P.DmgAtPlates.tttck or "verticalUp"
P.DmgAtPlates.crt = P.DmgAtPlates.crt or "verticalUp"
P.DmgAtPlates.ntttckndcrt = P.DmgAtPlates.ntttckndcrt or "verticalUp"
P.DmgAtPlates.pttht = P.DmgAtPlates.pttht or false
P.DmgAtPlates.ttpht = P.DmgAtPlates.ttpht or false
P.DmgAtPlates.petttht = P.DmgAtPlates.petttht or false
P.DmgAtPlates.shwrhll = P.DmgAtPlates.shwrhll or false
P.DmgAtPlates.hcrt = P.DmgAtPlates.hcrt or "verticalUp"
P.DmgAtPlates.nhcrt = P.DmgAtPlates.nhcrt or "verticalUp"
P.DmgAtPlates.hlclr = P.DmgAtPlates.hlclr or "0fff00"
P.DmgAtPlates.sfap = P.DmgAtPlates.sfap or false